//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rivals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rivals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ################
        ///#              #
        ///#              #
        ///#              #
        ///#     P        #
        ///#              #
        ///#              #
        ///#              #
        ///#              #
        ///#              #
        ///#         P    #
        ///#              #
        ///#              #
        ///#              #
        ///#              #
        ///################.
        /// </summary>
        internal static string Dungeon1 {
            get {
                return ResourceManager.GetString("Dungeon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####################
        ///#P          #     # #
        ///# ######### # # # # #
        ///#     #   # # # #   #
        ///##### # ### ### #####
        ///# #   #   #     #   #
        ///# # ##### ####### # #
        ///# #     # #   #   # #
        ///#T##### # # # # ### #
        ///# #       # # # #   #
        ///# # ### # # # # # ###
        ///#   #   # # #   #   #
        ///##### ### # # ##### #
        ///# #   #   # #       #
        ///# # ####### # # ### #
        ///#   #     # # #   # #
        ///##### # # #   ##### #
        ///#   # # #   #   #   #
        ///# ### # ####### # ###
        ///#     #             P
        ///#####################.
        /// </summary>
        internal static string Dungeon2 {
            get {
                return ResourceManager.GetString("Dungeon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####################
        ///#P    #   # #   #   #
        ///# ### # # # # # # # #
        ///#   # # # #   #   # #
        ///# ### # # ##### # # #
        ///#   #   # #     # # #
        ///### ### # ####### # #
        ///# #               # #
        ///# # # ####### # # # #
        ///#   #     #   #P#   #
        ///##### ### # # #######
        ///#     #   # #       #
        ///# ##### ### ####### #
        ///# #   #     #       #
        ///# # # # ##### ## ####
        ///# # #       # #     #
        ///# # #######   ### # #
        ///#     #   # #   # # #
        ///### # # # ##### # # #
        ///#   #   #         # P
        ///#####################.
        /// </summary>
        internal static string Dungeon3 {
            get {
                return ResourceManager.GetString("Dungeon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####################
        ///P #         #      P#
        ///# # # ##### # # ### #
        ///#   # #   #   # #   #
        ///# # # # # ##### # ###
        ///# # # # # #     #   #
        ///# # # # # # # ### ###
        ///# #   # # # #   #   #
        ///# ## ## #   # ##### #
        ///#         # #       #
        ///# ##### ### ##### # #
        ///#       #   # #   # #
        ///# ####### ### # ### #
        ///#   #       #     # #
        ///### # # ### ## ## # #
        ///#   # #   # #   #   #
        ///# ### # ### # # ### #
        ///#   # # #     # # # #
        ///### # # # ##### # # #
        ///#P    #   #     #  P#
        ///#####################.
        /// </summary>
        internal static string Dungeon4 {
            get {
                return ResourceManager.GetString("Dungeon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #####################
        ///P #     #          P#
        ///# # ### # ####### # #
        ///#   # #     #     # #
        ///# # # ##### # ##### #
        ///# # #           #   #
        ///# # ### #### #### # #
        ///#     #   #       # #
        ///# ### ### # # ##### #
        ///# # #   # P # #   # #
        ///# # ### ##### ### # #
        ///# #   #     #   #   #
        ///# ### ##### ### # # #
        ///# # # #     # # # # #
        ///# # # # ##### # # # #
        ///# # # #     #     # #
        ///# # # # ### ####### #
        ///# #   #   #   #   # #
        ///# # # ##### # # # # #
        ///#P  #       #   #   P
        ///#####################.
        /// </summary>
        internal static string Dungeon5 {
            get {
                return ResourceManager.GetString("Dungeon5", resourceCulture);
            }
        }
    }
}
